export const FORM_PROJECT = 'FORM_PROJECT';
export const GET_PROJECT = 'GET_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALID_PROJECTS = 'VALID_PROJECTS';
export const NOW_PROJECT = 'NOW_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';